title: Project Repository
author: Alexander Möllers
email: Alexander.j.moellers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Projects that have to do with AI or Computational Neuroscience. If you are interested to do something cool, reach out. 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
